"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 22:20:28.713662
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('theme', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('slug', name=op.f('uq_brands_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending_email_verification', 'active', 'deleted')", name=op.f('ck_users_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('auth_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('verify_email', 'reset_password')", name=op.f('ck_auth_tokens_purpose')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_tokens_token_hash'))
    )
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_table('earning_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('points >= 0', name=op.f('ck_earning_rules_points_positive')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_earning_rules_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_earning_rules')),
    sa.UniqueConstraint('brand_id', 'code', name=op.f('uq_earning_rules_brand_id_code'))
    )
    op.create_table('loyalty_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_loyalty_accounts_balance_not_negative')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_loyalty_accounts_brand_id_brands'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_loyalty_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_accounts')),
    sa.UniqueConstraint('user_id', 'brand_id', name=op.f('uq_loyalty_accounts_user_id_brand_id'))
    )
    op.create_table('pets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('species', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('breed', sa.String(length=80), nullable=True),
    sa.Column('food_preferences', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pets'))
    )
    op.create_index(op.f('ix_pets_user_id'), 'pets', ['user_id'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('redeemable', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('code_source', sa.String(length=20), nullable=False),
    sa.Column('valid_days', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost_points >= 0', name=op.f('ck_rewards_cost_points_positive')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_rewards_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rewards')),
    sa.UniqueConstraint('brand_id', 'slug', name=op.f('uq_rewards_brand_id_slug'))
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('has_dog', sa.Boolean(), nullable=True),
    sa.Column('dog_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_profiles'))
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anon_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_visitors_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitors')),
    sa.UniqueConstraint('anon_token_hash', name=op.f('uq_visitors_anon_token_hash'))
    )
    op.create_index(op.f('ix_visitors_user_id'), 'visitors', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('journey', sa.String(length=20), nullable=False),
    sa.Column('destination_path', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_policy', sa.String(length=30), nullable=False),
    sa.Column('registration_points', sa.Integer(), nullable=False),
    sa.Column('registration_points_on', sa.String(length=20), nullable=False),
    sa.Column('welcome_reward_id', sa.UUID(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("journey IN ('gamified', 'simple')", name=op.f('ck_campaigns_journey')),
    sa.CheckConstraint("registration_points_on IN ('registration', 'email_verified')", name=op.f('ck_campaigns_registration_points_on')),
    sa.CheckConstraint("scan_policy IN ('single_use', 'once_per_user', 'once_per_day', 'once_per_campaign', 'unlimited')", name=op.f('ck_campaigns_scan_policy')),
    sa.CheckConstraint('registration_points >= 0', name=op.f('ck_campaigns_registration_points_positive')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_campaigns_brand_id_brands'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['welcome_reward_id'], ['rewards.id'], name=op.f('fk_campaigns_welcome_reward_id_rewards'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('slug', name=op.f('uq_campaigns_slug'))
    )
    op.create_index(op.f('ix_campaigns_brand_id'), 'campaigns', ['brand_id'], unique=False)
    op.create_table('point_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount <> 0', name=op.f('ck_point_transactions_amount_not_zero')),
    sa.ForeignKeyConstraint(['account_id'], ['loyalty_accounts.id'], name=op.f('fk_point_transactions_account_id_loyalty_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_point_transactions')),
    sa.UniqueConstraint('account_id', 'source_type', 'source_id', name=op.f('uq_point_transactions_account_id_source_type_source_id'))
    )
    op.create_index(op.f('ix_point_transactions_account_id'), 'point_transactions', ['account_id'], unique=False)
    op.create_table('promo_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reward_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'assigned', 'used', 'expired')", name=op.f('ck_promo_codes_status')),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], name=op.f('fk_promo_codes_reward_id_rewards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_promo_codes_code'))
    )
    op.create_index(op.f('ix_promo_codes_reward_id'), 'promo_codes', ['reward_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('text_version', sa.String(length=40), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_consents_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_events_brand_id_brands'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_events_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('fk_events_visitor_id_visitors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('requires_account', sa.Boolean(), nullable=False),
    sa.Column('play_limit', sa.String(length=30), nullable=False),
    sa.Column('max_plays', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("play_limit IN ('unlimited', 'once', 'once_per_day', 'once_per_campaign', 'max_count')", name=op.f('ck_games_play_limit')),
    sa.CheckConstraint("type IN ('dog_race', 'roulette')", name=op.f('ck_games_type')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_games_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games')),
    sa.UniqueConstraint('campaign_id', 'type', name=op.f('uq_games_campaign_id_type'))
    )
    op.create_table('gtins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gtin', sa.String(length=14), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_gtins_brand_id_brands'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_gtins_campaign_id_campaigns'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gtins')),
    sa.UniqueConstraint('gtin', name=op.f('uq_gtins_gtin'))
    )
    op.create_index(op.f('ix_gtins_campaign_id'), 'gtins', ['campaign_id'], unique=False)
    op.create_table('reward_redemptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reward_id', sa.UUID(), nullable=False),
    sa.Column('promo_code_id', sa.UUID(), nullable=False),
    sa.Column('point_transaction_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=160), nullable=False),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['point_transaction_id'], ['point_transactions.id'], name=op.f('fk_reward_redemptions_point_transaction_id_point_transactions')),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], name=op.f('fk_reward_redemptions_promo_code_id_promo_codes')),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], name=op.f('fk_reward_redemptions_reward_id_rewards'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reward_redemptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reward_redemptions')),
    sa.UniqueConstraint('point_transaction_id', name=op.f('uq_reward_redemptions_point_transaction_id')),
    sa.UniqueConstraint('promo_code_id', name=op.f('uq_reward_redemptions_promo_code_id')),
    sa.UniqueConstraint('source', 'source_ref', name=op.f('uq_reward_redemptions_source_source_ref'))
    )
    op.create_index(op.f('ix_reward_redemptions_user_id'), 'reward_redemptions', ['user_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gtin', sa.String(length=14), nullable=False),
    sa.Column('serial', sa.String(length=20), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('accepted', 'already_used', 'campaign_inactive')", name=op.f('ck_scans_status')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_scans_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scans_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('fk_scans_visitor_id_visitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_scans_idempotency_key'))
    )
    op.create_index(op.f('ix_scans_campaign_id'), 'scans', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_scans_gtin'), 'scans', ['gtin'], unique=False)
    op.create_index(op.f('ix_scans_visitor_id'), 'scans', ['visitor_id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('limit_key', sa.String(length=160), nullable=True),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_game_sessions_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_sessions_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_game_sessions_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_game_sessions_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('fk_game_sessions_visitor_id_visitors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_sessions')),
    sa.UniqueConstraint('game_id', 'limit_key', name=op.f('uq_game_sessions_game_id_limit_key'))
    )
    op.create_index(op.f('ix_game_sessions_game_id'), 'game_sessions', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_sessions_user_id'), 'game_sessions', ['user_id'], unique=False)
    op.create_table('participations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('eligibility_key', sa.String(length=160), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_participations_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_participations_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_participations_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('fk_participations_visitor_id_visitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participations')),
    sa.UniqueConstraint('campaign_id', 'eligibility_key', name=op.f('uq_participations_campaign_id_eligibility_key'))
    )
    op.create_index(op.f('ix_participations_user_id'), 'participations', ['user_id'], unique=False)
    op.create_index(op.f('ix_participations_visitor_id'), 'participations', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participations_visitor_id'), table_name='participations')
    op.drop_index(op.f('ix_participations_user_id'), table_name='participations')
    op.drop_table('participations')
    op.drop_index(op.f('ix_game_sessions_user_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_game_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_scans_visitor_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_gtin'), table_name='scans')
    op.drop_index(op.f('ix_scans_campaign_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_reward_redemptions_user_id'), table_name='reward_redemptions')
    op.drop_table('reward_redemptions')
    op.drop_index(op.f('ix_gtins_campaign_id'), table_name='gtins')
    op.drop_table('gtins')
    op.drop_table('games')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_promo_codes_reward_id'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_point_transactions_account_id'), table_name='point_transactions')
    op.drop_table('point_transactions')
    op.drop_index(op.f('ix_campaigns_brand_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_visitors_user_id'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_profiles')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_pets_user_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_table('loyalty_accounts')
    op.drop_table('earning_rules')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_table('users')
    op.drop_table('brands')
    # ### end Alembic commands ###
