"""user registration campaign

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 22:27:40.868758
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_campaign_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_users_registration_campaign_id_campaigns'), 'users', 'campaigns', ['registration_campaign_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_registration_campaign_id_campaigns'), 'users', type_='foreignkey')
    op.drop_column('users', 'registration_campaign_id')
    # ### end Alembic commands ###
